//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentEditorShared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluentEditorShared.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tool that helps demonstrate the flexibility of the Fluent Design System as well as supports the app development process by generating XAML markup for our ResourceDictionary framework used in Universal Windows Platform (UWP) applications.
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluent XAML Theme Editor.
        /// </summary>
        internal static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string ApplyButtonText {
            get {
                return ResourceManager.GetString("ApplyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButtonPreviewText {
            get {
                return ResourceManager.GetString("CancelButtonPreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps to {0}.
        /// </summary>
        internal static string ColorFlyoutMappingDescription {
            get {
                return ResourceManager.GetString("ColorFlyoutMappingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Preview.
        /// </summary>
        internal static string ControlBorderThicknessPreview {
            get {
                return ResourceManager.GetString("ControlBorderThicknessPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Thickness.
        /// </summary>
        internal static string ControlBorderThicknessSectionHeader {
            get {
                return ResourceManager.GetString("ControlBorderThicknessSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Preview.
        /// </summary>
        internal static string ControlCornerRadiusPreview {
            get {
                return ResourceManager.GetString("ControlCornerRadiusPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        internal static string ControlPaletteBaseBlock {
            get {
                return ResourceManager.GetString("ControlPaletteBaseBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        internal static string ControlPaletteDarkTestContent {
            get {
                return ResourceManager.GetString("ControlPaletteDarkTestContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        internal static string ControlPaletteDarkThemeBlock {
            get {
                return ResourceManager.GetString("ControlPaletteDarkThemeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avares://FluentEditorShared/Resources/controlPaletteData.json.
        /// </summary>
        internal static string ControlPaletteDataPath {
            get {
                return ResourceManager.GetString("ControlPaletteDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ControlPaletteErrorOkButtonCaption {
            get {
                return ResourceManager.GetString("ControlPaletteErrorOkButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ControlPaletteExportButton {
            get {
                return ResourceManager.GetString("ControlPaletteExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string ControlPaletteInspectorHeader {
            get {
                return ResourceManager.GetString("ControlPaletteInspectorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        internal static string ControlPaletteLightTestContent {
            get {
                return ResourceManager.GetString("ControlPaletteLightTestContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        internal static string ControlPaletteLightThemeBlock {
            get {
                return ResourceManager.GetString("ControlPaletteLightThemeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string ControlPaletteLoadButton {
            get {
                return ResourceManager.GetString("ControlPaletteLoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load file {0}.
        /// </summary>
        internal static string ControlPaletteLoadError {
            get {
                return ResourceManager.GetString("ControlPaletteLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load.
        /// </summary>
        internal static string ControlPaletteLoadErrorTitle {
            get {
                return ResourceManager.GetString("ControlPaletteLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string ControlPalettePresetComboPlaceholderText {
            get {
                return ResourceManager.GetString("ControlPalettePresetComboPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        internal static string ControlPalettePrimaryBlock {
            get {
                return ResourceManager.GetString("ControlPalettePrimaryBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string ControlPaletteRegionBlock {
            get {
                return ResourceManager.GetString("ControlPaletteRegionBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset colors.
        /// </summary>
        internal static string ControlPaletteResetButton {
            get {
                return ResourceManager.GetString("ControlPaletteResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ControlPaletteSaveButton {
            get {
                return ResourceManager.GetString("ControlPaletteSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save file {0}.
        /// </summary>
        internal static string ControlPaletteSaveError {
            get {
                return ResourceManager.GetString("ControlPaletteSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save.
        /// </summary>
        internal static string ControlPaletteSaveErrorTitle {
            get {
                return ResourceManager.GetString("ControlPaletteSaveErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string ControlsCornerRadiusSliderHeader {
            get {
                return ResourceManager.GetString("ControlsCornerRadiusSliderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corner Radius.
        /// </summary>
        internal static string CornerRadiusSectionHeader {
            get {
                return ResourceManager.GetString("CornerRadiusSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Text.
        /// </summary>
        internal static string DarkThemeTextContrastTitle {
            get {
                return ResourceManager.GetString("DarkThemeTextContrastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string DefaultItemText {
            get {
                return ResourceManager.GetString("DefaultItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about contrast ratios.
        /// </summary>
        internal static string ExpandedColorPaletteEntryEditorContrastInfoButton {
            get {
                return ResourceManager.GetString("ExpandedColorPaletteEntryEditorContrastInfoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast Ratio Information.
        /// </summary>
        internal static string ExpandedColorPaletteEntryEditorContrastRatioTitle {
            get {
                return ResourceManager.GetString("ExpandedColorPaletteEntryEditorContrastRatioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert Color.
        /// </summary>
        internal static string ExpandedColorPaletteEntryEditorRevertButton {
            get {
                return ResourceManager.GetString("ExpandedColorPaletteEntryEditorRevertButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        internal static string ExportCopyButton {
            get {
                return ResourceManager.GetString("ExportCopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about XAML ResourceDictionary.
        /// </summary>
        internal static string ExportLearnMoreButton {
            get {
                return ResourceManager.GetString("ExportLearnMoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Text.
        /// </summary>
        internal static string LightThemeTextContrastTitle {
            get {
                return ResourceManager.GetString("LightThemeTextContrastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avares://FluentEditorShared/Resources/demodata.json.
        /// </summary>
        internal static string MainDataPath {
            get {
                return ResourceManager.GetString("MainDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKButtonPreviewText {
            get {
                return ResourceManager.GetString("OKButtonPreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        internal static string OverlayCornerRadiusHeader {
            get {
                return ResourceManager.GetString("OverlayCornerRadiusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Preview.
        /// </summary>
        internal static string OverlayCornerRadiusPreview {
            get {
                return ResourceManager.GetString("OverlayCornerRadiusPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Rounding, Thicker Borders.
        /// </summary>
        internal static string PreFluent {
            get {
                return ResourceManager.GetString("PreFluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yolo.
        /// </summary>
        internal static string TestContentAppBarButton {
            get {
                return ResourceManager.GetString("TestContentAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.
        /// </summary>
        internal static string TestContentButtonsBlock {
            get {
                return ResourceManager.GetString("TestContentButtonsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar view.
        /// </summary>
        internal static string TestContentCalendarViewBlock {
            get {
                return ResourceManager.GetString("TestContentCalendarViewBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkbox.
        /// </summary>
        internal static string TestContentCheckboxBlock {
            get {
                return ResourceManager.GetString("TestContentCheckboxBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        internal static string TestContentCheckedCheckbox {
            get {
                return ResourceManager.GetString("TestContentCheckedCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        internal static string TestContentCheckedRadio {
            get {
                return ResourceManager.GetString("TestContentCheckedRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo box.
        /// </summary>
        internal static string TestContentComboBlock {
            get {
                return ResourceManager.GetString("TestContentComboBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 1.
        /// </summary>
        internal static string TestContentComboItem1 {
            get {
                return ResourceManager.GetString("TestContentComboItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 2.
        /// </summary>
        internal static string TestContentComboItem2 {
            get {
                return ResourceManager.GetString("TestContentComboItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 3.
        /// </summary>
        internal static string TestContentComboItem3 {
            get {
                return ResourceManager.GetString("TestContentComboItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command bar.
        /// </summary>
        internal static string TestContentCommandBarBlock {
            get {
                return ResourceManager.GetString("TestContentCommandBarBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date picker.
        /// </summary>
        internal static string TestContentDatePickerBlock {
            get {
                return ResourceManager.GetString("TestContentDatePickerBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled accent button.
        /// </summary>
        internal static string TestContentDisabledAccentButton {
            get {
                return ResourceManager.GetString("TestContentDisabledAccentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled button.
        /// </summary>
        internal static string TestContentDisabledButton {
            get {
                return ResourceManager.GetString("TestContentDisabledButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string TestContentDisabledCheckbox {
            get {
                return ResourceManager.GetString("TestContentDisabledCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string TestContentDisabledRadio {
            get {
                return ResourceManager.GetString("TestContentDisabledRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable item 1.
        /// </summary>
        internal static string TestContentEditableComboItem1 {
            get {
                return ResourceManager.GetString("TestContentEditableComboItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable item 2.
        /// </summary>
        internal static string TestContentEditableComboItem2 {
            get {
                return ResourceManager.GetString("TestContentEditableComboItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable item 3.
        /// </summary>
        internal static string TestContentEditableComboItem3 {
            get {
                return ResourceManager.GetString("TestContentEditableComboItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled accent button.
        /// </summary>
        internal static string TestContentEnabledAccentButton {
            get {
                return ResourceManager.GetString("TestContentEnabledAccentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled button.
        /// </summary>
        internal static string TestContentEnabledButton {
            get {
                return ResourceManager.GetString("TestContentEnabledButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List view.
        /// </summary>
        internal static string TestContentListviewBlock {
            get {
                return ResourceManager.GetString("TestContentListviewBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Howdy! (disabled).
        /// </summary>
        internal static string TestContentListviewItem1 {
            get {
                return ResourceManager.GetString("TestContentListviewItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aloha! (selected).
        /// </summary>
        internal static string TestContentListviewItem2 {
            get {
                return ResourceManager.GetString("TestContentListviewItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        internal static string TestContentListviewItem3 {
            get {
                return ResourceManager.GetString("TestContentListviewItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola!.
        /// </summary>
        internal static string TestContentListviewItem4 {
            get {
                return ResourceManager.GetString("TestContentListviewItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio button.
        /// </summary>
        internal static string TestContentRadioBlock {
            get {
                return ResourceManager.GetString("TestContentRadioBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        internal static string TestContentSliderBlock {
            get {
                return ResourceManager.GetString("TestContentSliderBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textbox.
        /// </summary>
        internal static string TestContentTextboxBlock {
            get {
                return ResourceManager.GetString("TestContentTextboxBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text here.
        /// </summary>
        internal static string TestContentTextboxPlaceholderText {
            get {
                return ResourceManager.GetString("TestContentTextboxPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third state.
        /// </summary>
        internal static string TestContentThirdStateCheckbox {
            get {
                return ResourceManager.GetString("TestContentThirdStateCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time picker.
        /// </summary>
        internal static string TestContentTimePickerBlock {
            get {
                return ResourceManager.GetString("TestContentTimePickerBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle switch.
        /// </summary>
        internal static string TestContentToggleBlock {
            get {
                return ResourceManager.GetString("TestContentToggleBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle button.
        /// </summary>
        internal static string TestContentToggleButton {
            get {
                return ResourceManager.GetString("TestContentToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggled button.
        /// </summary>
        internal static string TestContentToggledButton {
            get {
                return ResourceManager.GetString("TestContentToggledButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchecked.
        /// </summary>
        internal static string TestContentUncheckedCheckbox {
            get {
                return ResourceManager.GetString("TestContentUncheckedCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchecked.
        /// </summary>
        internal static string TestContentUncheckedRadio {
            get {
                return ResourceManager.GetString("TestContentUncheckedRadio", resourceCulture);
            }
        }
    }
}
